version: '3.8'

services:
  manager:
    build:
      context: ../../crack-manager
    container_name: manager
    ports:
      - "8080:8080"
    networks:
      - app-network

  worker1:
    build:
      context: ..
    container_name: worker1
    ports:
      - "8081:8080"
    networks:
      - app-network
    environment:
      - SERVER_PORT=8080

  worker2:
    build:
      context: ..
    container_name: worker2
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      - SERVER_PORT=8080

  worker3:
    build:
      context: ..
    container_name: worker3
    ports:
      - "8083:8080"
    networks:
      - app-network
    environment:
      - SERVER_PORT=8080

networks:
  app-network:
    driver: bridge
